### ISSUE TITLE
Please Wrap Eval in Unit Tests with a Binding

### ISSUE THREAD

**Issue by Artiavis** [clj-commons/primitive-math#8]
At my employer, when attempting to import the source for your lib, I hit an "interesting" quirk of the compiler/runtime, which is only (mostly?) relevant when running your unit tests under a non-Lein non-Boot toolchain (specifically one which does not give a `binding` for `*ns*`):

Your[ `use-primitive-operators` and `unuse-primitive-operators`](https://github.com/ztellman/primitive-math/blob/7654d4c86a6a93639dd4d6d074a1fcb5ee64ebc2/src/primitive_math.clj#L170-L187) functions use the local value of `*ns*` to decide which functions to `ns-unmap`. At the REPL, or in a top-level form in a new `ns`, this is fine and works as expected. 

However, within a testing apparatus, `*ns*` may default to the root value of the `clojure.lang.Var`, which is `clojure.core`. In such cases, these macros will mangle the `clojure.core` namespace interns. This is an issue because [your test code calls eval at runtime](https://github.com/ztellman/primitive-math/blob/7654d4c86a6a93639dd4d6d074a1fcb5ee64ebc2/test/primitive_math_test.clj#L40-L65). If and when `clojure.core`'s namespace mappings get mangled as such, you cannot finish `eval`ing because the `==` references will be gone from `clojure.core`.

I guess this is a bug report for the test suite, because it doesn't make sense to call those functions within user-space application code. Could you please add a `(binding [*ns* *ns*] (in-ns 'other) (refer-clojure) ...)` block (or the like) to the `eval` block as a matter of hygiene? Thanks!

**Comment by KingMob** [comment]
Hi @Artiavis, thanks for sharing. 

We're making a final change to support Graal use, but for most intents, this library is archived, unless non-test bugs are found. Supporting alternative testing setups is not something I have time for, even if the project was active. Sorry about that.
